### ISSUE TITLE
Lier les différents fichiers Markdown

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/schema-web#1]
Je remarque sur https://github.com/etalab/schema-irve qu'il y a plusieurs fichiers Markdown :
- README
- CONTEXT
- SEE_ALSO
- CHANGELOG

La version actuellement en prod gère le README comme page d'accueil et met un lien vers le dernier CHANGELOG s'il est disponible. Voir par exemple https://schema-datagouv.antoine-augusti.fr/etalab/schema-irve/latest.html

https://github.com/AntoineAugusti/schema-web/blob/6c11c57a7866369d6b6df3bd189c1c8736690ee9/_layouts/schema.html#L15-L35

Comment gérer les autres fichiers ?

**Comment by AntoineAugusti** [comment]
cc @abulte @taniki

**Comment by AntoineAugusti** [comment]
Si @johanricher tu as un avis

**Comment by johanricher** [comment]
Nous en avons justement réfléchi hier avec @cbenz et @pierredittgen.
Ces différents fichiers Markdown (parfois appelés "ressources complémentaires") n'ont jamais été une solution satisfaisante et nous sommes effectivement persuadés qu'il faut remettre le README au centre de la documentation. Dans le cas du SCDL où OpenDataFrance souhaite traduire le modèle de données colonne par colonne ([exemple](https://scdl.opendatafrance.net/docs/schemas/scdl-irve.html)) nous allons préconiser que cela apparaisse directement dans le README.
Concrètement : la page de documentation de chaque schéma sur scdl.opendatafrance.net serait un rendu de leur README ; on outillerait alors les mainteneurs de schémas (tels qu'ODF) pour qu'il puisse facilement générer ce `README.md` à partir du `schema.json`, auquel viendraient s'ajouter le contenu des "ressources complémentaires" actuelles.
L'idée d'un template [soulevée précédemment](https://framagit.org/jailbreak/table-schema-to-markdown/issues/1) interviendrait logiquement dans ce nouveau mécanisme.

**Comment by abulte** [comment]
@johanricher donc on peut partir sur l'affichage d'un README de ce côté ci, peu importe depuis quoi/comment il a été généré de ce côté-là ?

**Comment by johanricher** [comment]
Les exigences que je cite sont seulement côté SCDL où la doc des schémas doit être normalisée. Mais ça arrangerait tout le monde qu'on s'accorde sur le fait que le README contienne à l'avenir tout ce qu'il y a dans cette doc IRVE : https://scdl.opendatafrance.net/docs/schemas/scdl-irve.html (et peu importe comment il est généré, oui).

**Comment by AntoineAugusti** [comment]
Je préférerais qu'on normalise plusieurs fichiers / sections et que schema.data.gouv.fr génère automatiquement un fichier README (ou fasse des liens vers ces autres fichiers) contenant ces diverses sections, certaines générées automatiquement comme le modèle de données à partir du `schema.json` pour des schémas Table Schema

**Comment by AntoineAugusti** [comment]
Ça peut être une règle qui dit : si j'ai des fichiers CONTEXT et SEE_ALSO, ils sont concaténés avec le README pour afficher sur un seul bloc : README puis CONTEXT puis SEE_ALSO

**Comment by abulte** [comment]
Il faut garder à l'esprit, je pense, que schema.data.gouv.fr n'est pas réservé aux schémas TableSchema. De ce point de vue, c'est peut-être cohérent de ne pas embarquer trop de logique spécifique à ces schémas dans ce dépôt. Quitte à proposer un autre outillage pour équiper des dépôts accueillant des TablesSchema.

**Comment by johanricher** [comment]
> Je préférerais (...) que schema.data.gouv.fr génère automatiquement un fichier README 

Sauf que schema.data.gouv.fr ne pourra pas générer de README dans un dépôt non géré par Etalab.

Et quand bien même, cela amenerait une redondance avec des conséquences non souhaitables. Exemple : si le README est modifié à la main sur le dépot Git, ces changements seraient écrasés par la génération à partir des autres fichiers Markdown.

Pour être totalement transparent, nous réfléchissons de notre côté à un modèle de contribution communautaire et complètement ouvert pour un référencement plus large de schémas open data, et qui donnera peut-être jour à un nouveau site prochainement.
C'est pourquoi nous pensons qu'il faut streamliner tout ça et revenir aux fondamentaux et pratiques déjà adoptés par la majorité. Encore une fois, ces "ressources complémentaires" maintenues dans des fichiers Markdown séparés étaient une solution de secours, qui a fait long feu.

**Comment by AntoineAugusti** [comment]
Je clos ici. La discussion continue là-bas https://github.com/etalab/schema.data.gouv.fr/issues/15
